apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: federation
  name: books-service
spec:
  selector:
    matchLabels:
      name: books-service
  replicas: 1
  template:
    metadata:
      labels:
        name: books-service
    spec:
      containers:
        - name: books-service
          image: books-service:1
          imagePullPolicy: 'Never'
          ports:
            - containerPort: 4002