apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: federation
  name: gateway
spec:
  selector:
    matchLabels:
      name: gateway
  replicas: 2
  template:
    metadata:
      labels:
        name: gateway
    spec:
      containers:
        - name: gateway
          image: gateway:1
          imagePullPolicy: 'Never'
          ports:
            - containerPort: 4000