apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: federation
  name: users-service
spec:
  selector:
    matchLabels:
      name: users-service
  replicas: 1
  template:
    metadata:
      labels:
        name: users-service
    spec:
      containers:
        - name: users-service
          image: users-service:1
          imagePullPolicy: 'Never'
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m 
          ports:
            - containerPort: 4001